[package]
name = "combine_hgt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
ron = "0.8.0"
serde = { version = "1.0.163", features = ["derive"] }
